name: jw-masterthesis
channels:
  - vpython
  - defaults
  - pytorch
dependencies:
  - matplotlib=3.0.1
  - numpy=1.16.2
  - numpy-base=1.16.2
  - pandas=0.24.1
  - pip=19.1.1
  - pyqtgraph=0.10.0
  - python=3.6.6
  - pytorch=1.3.1
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - vpython=7.5.0
  - statsmodels=0.10.1
  - pyyaml=5.1.2
  - pip:
      - gym==0.12.0
      - pyinstrument==3.0.1
